#development specific settings

production:
  PORT: 3000
  SERVER_URL: 'https://movie-party.gocomet.com'
  SERVER_PORT: 80
  CLINT_URL: localhost
  TOKEN_NAME: "hack-xxx-comet-movie-party"
  DEBUG: false


development:
  PORT: 3001
  SERVER_URL: http://localhost
  SERVER_PORT: 3000
  CLINT_URL: localhost
  TOKEN_NAME: "hack-xxx-comet-movie-party"
  DEBUG: false
